# Generated by Django 5.2.6 on 2025-09-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Author_Account_creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='auttor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsportal.author'),
        ),
    ]
