# Generated by Django 5.2.6 on 2025-09-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0002_author_author_account_creation_date_post_auttor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auttor',
            new_name='author',
        ),
    ]
